#!/bin/bash

# assumes:
# - $1 is the config state of zerus-test and node-adm
# - "../node-adm" exists

BASECONFIG=$1
APPLYLOG=${PWD}/${BASECONFIG}-apply.log
CHECKLOG=${PWD}/${BASECONFIG}-check.log

cd .
./vboxvm ssh-forward off
./vboxvm vm delete
./vboxvm network delete
./vboxvm state load config ${BASECONFIG}
./vboxvm network create
./vboxvm vm create
./vboxvm ssh-forward on
cd -

cd ../../node-adm/
./zss0 state load config ${BASECONFIG}
SSHPORT=$(./zss0 env | grep "SECURE_PORT" | cut -d: -f2)
./zss0 sshclean
./zss0 sshwait
./zss0 sshcopy
./zss0 operate on
./zss0 apply | tee ${APPLYLOG}
./zss0 reboot
cd -

cd .
./vboxvm ssh-forward off
./vboxvm config rsshport ${SSHPORT}
./vboxvm ssh-forward on
cd -

cd ../../node-adm/
./zss0 sshwait
./zss0 config nodectl "ssh -p ${SSHPORT}"
./zss0 check | tee ${CHECKLOG}
cd -

cd ../../ceph-adm/
./zss0 state load config ${BASECONFIG}
./zss0 secret-create
./zss0 preflight
./zss0 network up
./zss0 mon up
./zss0 osd up
./zss0 mds up
cd -

