#!/bin/bash

# assumes:
# 1. ./01-* go
# 2. ./do operator on
# 3. ./02-* HOST IP DISKS LSSHPORT
# 4. ./do operator off
#
# examples:
# ./02-* u4 10.13.13.104 "10 10 10" 2204
# ./02-* u5 10.13.13.105 "10 10 10" 2205
# ./02-* u6 10.13.13.106 "10 10 10" 2206

NODE=${1:-u3}
IP=${2:-10.13.13.103}
DISKS=${3:-10 10 10}
LSSHPORT=${4:-2203}

echo "Require /etc/hosts to declare ${IP} ${NODE}."
grep ${IP} /etc/hosts | grep ${NODE} /etc/hosts || exit 1

cd repo/zerus-test/vboxvm
SSHPORT=$(./zss0 env RSSHPORT)
./zss0 config vmspec "$(./zss0 env VMSPEC) ${NODE}"
./zss0 config diskmap_ingb "( $(./zss0 env DISKMAP_INGB) [\"${NODE}\"]=\"${DISKS}\" )"
./zss0 config lsshports "( $(./zss0 env LSSHPORTS) [\"${NODE}\"]=\"${LSSHPORT}\" )"
./zss0 config rsshport 22
./zss0 vm create ${NODE}
./zss0 ssh-forward on ${NODE}
cd -

cd repo/node-adm/
./zss0 add ${NODE}
cd -

cd repo/zerus-test/vboxvm
./zss0 ssh-forward off ${NODE}
./zss0 config rsshport ${SSHPORT}
./zss0 ssh-forward on ${NODE}
cd -

cd repo/node-adm/
./zss0 sshwait ${NODE}
./zss0 check ${NODE}
cd -
