#!/bin/bash

# examples:
# ./04-* u2

NODES=${1:-u2 u3}

cd repo/ceph-adm/
./zss0 config monitors "$(./zss0 env MONITORS) ${NODES}"
./zss0 mon up ${NODES}
./zss0 config mdsnode "$(./zss0 env MDSNODE) ${NODES}"
./zss0 mds up ${NODES}
cd -

