#!/bin/bash

# examples:
# ./09-* u3

MASTERS=${1:-u3}

for MASTER in ${MASTERS}
do
	cd repo/kube-adm/
	./zss0 config masters "$(./zss0 env MASTERS) ${MASTER}"
	./zss0 preflight ${MASTER}
	./zss0 master-join ${NODE}
	cd -
done

cd repo/kube-adm/
./zss0 network down
./zss0 network up
cd -
