#!/bin/bash

# examples:
# ./11-* u3

NODES=${1:-u3}

for NODE in ${NODES}
do
	cd repo/kube-adm/
	./zss0 leave ${NODE}
	./zss0 clean ${NODE}
	./zss0 config workers "$(./zss0 env WORKERS | sed "s/${NODE}//g")"
	cd -
done

cd repo/kube-adm/
./zss0 network down
./zss0 network up
cd -
