#!/bin/bash

ACTION=$1
NAMESPACE=$2
PVCNAME=$3
CAPACITY=$4
PATHNAME=$5
TYPENAME=$6

case ${ACTION} in
	"create")
		if [ "$NAMESPACE" == "" ] || [ "$PVCNAME" == "" ] || [ "$CAPACITY" == "" ] || [ "$PATHNAME" == "" ] || [ "$TYPENAME" == "" ] ; then
			echo Ex: $0 namespace pvc-name 5Gi /data/vol-path
			exit 1
		fi

		cat <<EOF | kubectl create -f -
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${NAMESPACE}-${PVCNAME}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: ${CAPACITY}
  claimRef:
    namespace: ${NAMESPACE}
    name: ${PVCNAME}
  cephfs:
    monitors:
      - 10.13.13.101:6789
    path: /kube-store/${NAMESPACE}/${TYPENAME}
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
EOF
		;;
	"delete")
		kubectl delete pv ${NAMESPACE}-${PVCNAME}
		;;
	"secret")
		cd $(dirname $0)/../../../ceph-adm/
		./zss0 kube-secret up ${NAMESPACE}
		cd -
		;;
esac
